Fix ldap.managed errors
Regression from 78e2a3e (#48666):
- AttributeError: 'tuple' object has no attribute 'encode'
- ValueError: too many values to unpack

Fixes: #52022.